config/routes.rb
AskMe::Application.routes.draw do
  
  
  devise_for :users, :path => 'user', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :path => 'admin', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}
  
  resources :users
  resources :questions
  resources :answers
  
  root :to => "application#index"
  
  

end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_accessible :helpful, :likes, :question, :user_id, :votes
  
  validates :question, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :user_id, presence: true
  belongs_to :user
  has_many :answers, :dependent => :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :authenticate_any!, :except => [:index, :show]
  
  add_breadcrumb "questions", :questions_path
  def index
    @questions = Question.all
    
    respond_to do |format|
    format.html  # index.html.erb
    format.json  { render :json => @questions }
    end
  end
  
  def show
    
        add_breadcrumb "show", question_path
    @question = Question.find(params[:id])
    @answer = @question.answers.new
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @question }
    end
  end
  
  def new
    add_breadcrumb "new", new_question_path

    @question = Question.new
  end
  
  def create
    @question = (current_user || current_admin).questions.new(params[:question])
    
    respond_to do |format|
      if @question.save
        format.html  { redirect_to(@question,
                      :notice => 'Question was successfully submitted.') }
        format.json  { render :json => @question,
                      :status => :created, :location => @question }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @question.errors,
                      :status => :unprocessable_entity }
      end
    end
    
  end
  
  def edit
    add_breadcrumb "edit", edit_question_path

     @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
 
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html  { redirect_to(@question,
                      :notice => 'Question was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @question.errors,
                      :status => :unprocessable_entity }
       end
    end
  
  end
  
  def destroy
     @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url,:notice => 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= form_for(@question) do |question_form| %>
    <%= render "shared/error_messages", :target => @question %>  
 
  
  <div class="field">
    <%= question_form.text_field(:question) %>
  </div>

 
<%= question_form.submit 'AskMe', :class => 'btn btn-inverse' %>

    <button type="button" class="btn btn-primary" data-loading-text="Loading...">Loading state</button>
 
<% end %>

app/views/questions/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h1>Edit Question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h1>Question Library</h1>
 
<table cellpadding="20px" border="1px" cellspacing="10px" class="table-hover">
  <tr>
    <th>Question</th>
    <% if user_signed_in? || admin_signed_in? %>
    <th>Edit</th>
    <th>Delete</th>
    <% end %>
  </tr>
 
<% @questions.each do |quest| %>
  <tr>
    <td><%= link_to quest.question, quest, 'data-toggle' => 'tooltip', 'title' => 'view question'%></td>
    <% if user_signed_in? || admin_signed_in? %>
    <td><%= link_to (image_tag'edit.png', size:"20x20", alt:"Edit_question"), edit_question_path(quest), 'title' => 'edit question' %></td>
    <td><%= link_to (image_tag'delete.png', size:"20x20", alt:"Delete_question"), quest, :confirm => 'Are you sure?',
                                     :method => :delete %></td>
    <% end %>
  </tr>
  
<% end %>
  
  
  <% if @questions.empty? %>
  <p>No questions found!</p>
  <% end  %>
</table>
 
<br />

<%  #new_post_path %>
<%= link_to 'AskMe new question?', new_question_path %>

app/views/questions/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
  
  <h1>New Question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div class="span10" style="border: solid 1px #666">

  <div class="navbar navbar-inverse" style="width: 730px;margin-left: -10px;margin-top: 10px;">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
        </a>
        <a class="brand">Question</a>
      </div>
    </div>
  </div>

  <div style="padding: 10px;">
    <p><strong>Question:</strong> <%= @question.question %></p>
    <b>asked by:</b> <%= link_to @question.user.email, @question.user %>
  </div>

</div>


<div class="span9" style="border: solid 1px #666;margin-top: 20px;margin-bottom: 20px;">

  <div class="navbar navbar-inverse" style="width: 657px;margin-left: -10px;margin-top: 10px;">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
        </a>
        <a class="brand">Answers</a>
      </div>
    </div>
  </div>

  <div style="padding: 10px;">
    <% @question.answers.each do |ans| %>
      <p><strong>Answer:</strong> <%= ans.answer %></p>
      <hr>
    
      
  <% if ans.answer == 0 %>
  <p>No solutions yet!</p>
  <% end  %>
<% end %>
  </div>
</div>

<div class="span4" style="margin-bottom: 20px;">

<a href="#myModal" role="button" class="btn btn-inverse" data-toggle="modal">Submit your answer</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Give Your Answer</h3>
</div>
<div class="modal-body">
<%= form_for(@answer) do |f| %>
    
  <%= render "shared/error_messages", :target => @answer %>  

      <p>
        <%= f.text_field :answer %>
        <%= f.hidden_field :question_id, :value => @question.id %>
      </p>

</div>
<div class="modal-footer">
<p>
        <%= f.submit 'Submit answer', :class => 'btn btn-inverse' %>
</p>
    <% end %>
</div>
</div>
</div>


<div class="span10" style="margin-top: 20px;margin-bottom: 20px;">

  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Back', questions_path %>
</div>