config/routes.rb
AskMe::Application.routes.draw do
  
  
  devise_for :users, :path => 'user', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :path => 'admin', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}
  
  resources :users
  resources :questions
  resources :answers
  
  root :to => "application#index"
  
  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AskMe - Clear your minds!" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= image_tag 'logo.png', id:"logo", size:"100x70"%>
              <a id="slogan" href="<%= root_url %>">AskMe - Find Solutions</a>

<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %> | 
  <%= render 'devise/menu/login_items' %>
</ul>

    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">Home</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Users", users_path  %></li>
              <li><%= link_to "Manage Questions", new_question_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <!--<li class="nav-header">Sidebar</li>-->
              <li><%= link_to "About Us", page_path("about")  %></li>
              <li><%= link_to "Question Library", questions_path  %></li>
              <li><%= link_to "Contact Us", page_path("contact")  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>Copyrights &copy; <%= link_to 'TechVerx' , 'http://www.techverx.com/'%>  Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AskMe - Clear your minds!" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body data-spy="scroll" data-target=".navbar">
    <script>
      $(function(){
       $("#techverx").popover();
  
      }); 
    </script>
    <%= image_tag 'logo.png', id:"logo", size:"100x70"%>
              <a id="slogan" href="<%= root_url %>">AskMe - Find Solutions</a>

<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %> | 
  <%= render 'devise/menu/login_items' %>
</ul>
              
              
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand icon-home" href="<%= root_url %>"> Home</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Users", users_path  %></li>
              <li><%= link_to "AskMe Question", new_question_path  %></li>
              <li class="dropdown"><a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/about">
                Dropdown<b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li>1...</li>
                  <li>2...</li>
                  <li>3...</li>
                </ul>
              </li>
              <li style="margin-top:5px;">
                <form class="form-search">
                <input type="text" class="search-query" />
                <button class="btn icon-search"></button>
              </form>          
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          
          <div class="span3">

            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                  <!--<li class="nav-header">Sidebar</li>-->
                  <li><%= link_to "About Us", page_path("about")  %></li>
                  <li><%= link_to "Question Library", questions_path  %></li>
                  <li><%= link_to "Contact Us", page_path("contact")  %></li>
                </ul>
            </div><!--/.well -->

            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                  <li class="nav-header">Latest Questions</li>
                    <%  @questions = Question.limit(5) %>
                    <% @questions.each do |quest| %>
                    <li><%= link_to quest.question, quest %></li>
                  <% end %>
                </ul>
            </div><!--/.well -->

          </div><!--/span-->

          <div class="span8">
            <%= bootstrap_flash %>
            <%= render_breadcrumbs(divider='/') %>
            <%= yield %>
          </div>      
                        
        </div>
      </div><!--/row-->

      <footer>
        <a href="#" id="techverx" rel="popover" data-content="bodyy" data-original-title="titleeee" >Techverxxx</a>
        <p>Copyrights &copy; <%= link_to 'TechVerx' , 'http://www.techverx.com/'%>  Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>